title: naming-convention-liquibase-gradle-plugin v1.0
description: "A lightweight Gradle plugin for validating XML, YAML/YML, JSON Liquibase changeLog files against a customizable set of structural and content rules.<br>Enables teams to enforce Liquibase changeLog standards across codebases with zero runtime dependencies and minimal configuration overhead."
theme: jekyll-theme-slate
